version: '3.6'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../:/var/www
    links:
      - php
    depends_on:
      - php
      - mysql

  php:
    volumes:
       - ../../:/var/www
    image: phpdockerio/php73-fpm

  mysql:
      image: mysql:8.0.17
      command:
          - echo "ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'lopata';" | mysql --user=root --password=lopata'
          #'--default-authentication-plugin=mysql_native_password'
      ports:
          - "33060:3306"
      environment:
#         MYSQL_DATABASE: 'db'
         MYSQL_USER: 'user'
         MYSQL_PASSWORD: 'lopata'
         MYSQL_ROOT_PASSWORD: 'lopata'
      volumes:
          - mysql_vstupni_test:/var/lib/mysql


volumes:
  mysql_vstupni_test:
